FROM node:21-alpine3.20 as dev
WORKDIR /usr/src/app
COPY package*.json ./
COPY yarn.lock ./
RUN yarn install

FROM node:21-alpine3.20 as build
WORKDIR /usr/src/app
# Argumentos del build
ARG VITE_SOCKET_HOST
ARG VITE_API_HOST
ENV VITE_SOCKET_HOST=$VITE_SOCKET_HOST
ENV VITE_API_HOST=$VITE_API_HOST
# Proceso de build
COPY --from=dev /usr/src/app/node_modules ./node_modules
COPY . .
RUN yarn build

FROM nginx:alpine3.18-slim as runner
# Configuracion del server
COPY --from=build /usr/src/app/dist /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY docker/nginx.conf /etc/nginx/conf.d

EXPOSE 80
CMD [ "nginx","-g", "daemon off;" ]
